package aleksandr.fedotkin.buyercryptomoney.core.exception

import aleksandr.fedotkin.core.exception.BaseException

class InvalidFormatNumberCardException : BaseException(INVALID_FORMAT_NUMBER_CARD_EXCEPTION)
class InvalidFormatCvcException : BaseException(INVALID_FORMAT_CVC_EXCEPTION)
class InvalidFormatMonthException : BaseException(INVALID_FORMAT_MONTH_EXCEPTION)
class InvalidFormatYearException : BaseException(INVALID_FORMAT_YEAR_EXCEPTION)
