package aleksandr.fedotkin.set.protocol.core

const val NETWORK_CALL_FAIL = -2
const val SAFE_CALL_FAIL = -1
const val BAD_REQUEST = 400
const val INTERNAL_SERVER_ERROR = 500
const val NO_INTERNET = 666
const val INVALID_FORMAT_NUMBER_CARD_EXCEPTION = 501
const val INVALID_FORMAT_CVC_EXCEPTION = 502
const val INVALID_FORMAT_MONTH_EXCEPTION = 503
const val INVALID_FORMAT_YEAR_EXCEPTION = 504
const val SIGNATURE_ERROR = 505
const val SET_ERROR = 506
const val UNKNOWN_RRPID = 507
const val THUMBS_MISMATCH = 508
const val CHALLENGE_MISMATCH = 509